name: CI

on:
  pull_request:
  push:
    branches:
      - main
      - misc

jobs:
  mix_test:
    name: mix test (Elixir ${{matrix.elixir}} | Erlang/OTP ${{matrix.otp}})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - elixir: 1.11.4
            otp: 21.3.8.24
          - elixir: 1.12.2
            otp: 24.0.4
          - elixir: 1.13.3
            otp: 24.3.2
            check_formatted: true
            warnings_as_errors: true
    env:
      MIX_ENV: test
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}
      - name: Install Dependencies
        run: |
          mix local.hex --force
          mix local.rebar --force
          mix deps.get --only test
      - name: Compile Dependencies
        run: mix deps.compile
      - run: mix format --check-formatted
        if: matrix.check_formatted
      - run: mix compile --warnings-as-errors=${{matrix.warnings_as_errors || false}}
      - run: mix test
